stages:
  - .pre
  - test
  - deploy

.pre-html-css: #vérification du html et du css
  stage: .pre
  tags:
    - docker
  image: node
  script:
    - npm install htmlhint stylelint stylelint-config-standard
    - npx htmlhint --config .htmlhint.rc Exercice-50.html > linthtml_report_exo50.txt
    - npx stylelint Exercice-50.css > lintcss_report_exo50.txt
  artifacts:
    paths:
      - linthtml_report_exo50.txt
      - lintcss_report_exo50.txt

.pre-js: #vérification du javascript
  stage: .pre
  tags:
    - docker
  image: node
  script:
    - npm install eslint
    - npx eslint Exercice-50.js > lintes_report_exo50.txt
  artifacts:
    paths:
      - lintes_report_exo50.txt

jobcypress: #test du code avec cypress
  stage: test
  tags:
    - docker  # Comme on utilise une image pour isoler on doit utiliser un runner docker
  image: cypress/base:10 # Image fournie par cypress avec ce qu'il faut
  script:
    - npm i # Installe ce qui est décrit dans package.json
    - ./node_modules/.bin/serve & # Lance le serveur
    - ./node_modules/.bin/cypress run # Lance les tests

pages: #depoiment de la page 
  stage: deploy
  script:
    - mkdir -p public
    - cp Exercice-50.html public/
  artifacts:
    paths:
      - public
